-- Seeder 001: Seed System Configuration and Users
-- Description: Seeds system settings, permissions, roles, and default users

-- Insert default system settings (already inserted in migration, but ensure they exist)
INSERT INTO system_settings (setting_key, setting_value, setting_type, description, category, is_system, is_editable) VALUES
('app_name', 'School Management System', 'STRING', 'Application name', 'GENERAL', true, false),
('app_version', '1.0.0', 'STRING', 'Application version', 'GENERAL', true, false),
('maintenance_mode', 'false', 'BOOLEAN', 'System maintenance mode', 'GENERAL', true, true),
('max_login_attempts', '5', 'INTEGER', 'Maximum failed login attempts before lockout', 'SECURITY', true, true),
('lockout_duration_minutes', '30', 'INTEGER', 'Account lockout duration in minutes', 'SECURITY', true, true),
('session_timeout_minutes', '60', 'INTEGER', 'User session timeout in minutes', 'SECURITY', true, true),
('password_expiry_days', '90', 'INTEGER', 'Password expiry duration in days', 'SECURITY', true, true),
('backup_retention_days', '30', 'INTEGER', 'Backup retention period in days', 'BACKUP', true, true),
('auto_backup_enabled', 'true', 'BOOLEAN', 'Enable automated backups', 'BACKUP', true, true),
('auto_backup_schedule', '0 2 * * *', 'STRING', 'Automated backup cron schedule', 'BACKUP', true, true),
('file_upload_max_size_mb', '10', 'INTEGER', 'Maximum file upload size in MB', 'FILES', true, true),
('allowed_file_types', 'pdf,doc,docx,xls,xlsx,jpg,jpeg,png', 'STRING', 'Allowed file types for upload', 'FILES', true, true),
('student_photo_max_size_mb', '2', 'INTEGER', 'Maximum student photo size in MB', 'FILES', true, true),
('report_generation_timeout_seconds', '300', 'INTEGER', 'Report generation timeout in seconds', 'REPORTS', true, true),
('max_concurrent_reports', '5', 'INTEGER', 'Maximum concurrent report generations', 'REPORTS', true, true),
('audit_log_retention_days', '365', 'INTEGER', 'Audit log retention period in days', 'AUDIT', true, true),
('system_log_retention_days', '30', 'INTEGER', 'System log retention period in days', 'AUDIT', true, true),
('enable_api_logging', 'true', 'BOOLEAN', 'Enable API request logging', 'AUDIT', true, true),
('enable_user_activity_logging', 'true', 'BOOLEAN', 'Enable user activity logging', 'AUDIT', true, true),
('default_language', 'en', 'STRING', 'Default application language', 'LOCALIZATION', true, true),
('timezone', 'UTC', 'STRING', 'System timezone', 'LOCALIZATION', true, true),
('date_format', 'YYYY-MM-DD', 'STRING', 'Default date format', 'LOCALIZATION', true, true),
('time_format', 'HH24:MI', 'STRING', 'Default time format', 'LOCALIZATION', true, true),
('currency_symbol', '$', 'STRING', 'Default currency symbol', 'LOCALIZATION', true, true),
('currency_code', 'USD', 'STRING', 'Default currency code', 'LOCALIZATION', true, true),
('decimal_places', '2', 'INTEGER', 'Number of decimal places for currency', 'LOCALIZATION', true, true),
('enable_multi_language', 'true', 'BOOLEAN', 'Enable multi-language support', 'LOCALIZATION', true, true),
('supported_languages', 'en,ne', 'STRING', 'Supported languages (comma separated)', 'LOCALIZATION', true, true)
ON CONFLICT (setting_key) DO NOTHING;

-- Insert default permissions (already inserted in migration, but ensure they exist)
INSERT INTO permissions (permission_name, permission_code, description, module, category, permission_level, is_system, is_active) VALUES
('View Dashboard', 'DASHBOARD_VIEW', 'View system dashboard', 'DASHBOARD', 'GENERAL', 'VIEW', true, true),
('Manage System Settings', 'SYSTEM_SETTINGS_MANAGE', 'Manage system-wide settings', 'SYSTEM', 'ADMIN', 'ADMIN', true, true),
('View System Logs', 'SYSTEM_LOGS_VIEW', 'View system logs and monitoring', 'SYSTEM', 'AUDIT', 'VIEW', true, true),
('Manage Users', 'USERS_MANAGE', 'Create, update, and delete users', 'USERS', 'ADMIN', 'ADMIN', true, true),
('View Users', 'USERS_VIEW', 'View user information', 'USERS', 'GENERAL', 'VIEW', true, true),
('Manage Roles', 'ROLES_MANAGE', 'Manage user roles and permissions', 'USERS', 'ADMIN', 'ADMIN', true, true),
('Manage Schools', 'SCHOOLS_MANAGE', 'Create, update, and delete schools', 'SCHOOLS', 'ADMIN', 'ADMIN', true, true),
('View Schools', 'SCHOOLS_VIEW', 'View school information', 'SCHOOLS', 'GENERAL', 'VIEW', true, true),
('Manage Students', 'STUDENTS_MANAGE', 'Create, update, and delete students', 'STUDENTS', 'ADMIN', 'ADMIN', true, true),
('View Students', 'STUDENTS_VIEW', 'View student information', 'STUDENTS', 'GENERAL', 'VIEW', true, true),
('Manage Exams', 'EXAMS_MANAGE', 'Create, update, and delete exams', 'EXAMS', 'ADMIN', 'ADMIN', true, true),
('View Exams', 'EXAMS_VIEW', 'View exam information', 'EXAMS', 'GENERAL', 'VIEW', true, true),
('Manage Results', 'RESULTS_MANAGE', 'Manage exam results and grades', 'EXAMS', 'ADMIN', 'ADMIN', true, true),
('View Results', 'RESULTS_VIEW', 'View exam results', 'EXAMS', 'GENERAL', 'VIEW', true, true),
('Manage Fees', 'FEES_MANAGE', 'Create, update, and delete fee structures', 'FEES', 'ADMIN', 'ADMIN', true, true),
('View Fees', 'FEES_VIEW', 'View fee information', 'FEES', 'GENERAL', 'VIEW', true, true),
('Manage Certificates', 'CERTIFICATES_MANAGE', 'Create, update, and delete certificates', 'CERTIFICATES', 'ADMIN', 'ADMIN', true, true),
('View Certificates', 'CERTIFICATES_VIEW', 'View certificate information', 'CERTIFICATES', 'GENERAL', 'VIEW', true, true),
('Manage Reports', 'REPORTS_MANAGE', 'Create, update, and delete reports', 'REPORTS', 'ADMIN', 'ADMIN', true, true),
('View Reports', 'REPORTS_VIEW', 'View reports and analytics', 'REPORTS', 'GENERAL', 'VIEW', true, true),
('Manage Notifications', 'NOTIFICATIONS_MANAGE', 'Create, update, and delete notifications', 'NOTIFICATIONS', 'ADMIN', 'ADMIN', true, true),
('View Notifications', 'NOTIFICATIONS_VIEW', 'View notifications and announcements', 'NOTIFICATIONS', 'GENERAL', 'VIEW', true, true),
('Manage Documents', 'DOCUMENTS_MANAGE', 'Create, update, and delete documents', 'DOCUMENTS', 'ADMIN', 'ADMIN', true, true),
('View Documents', 'DOCUMENTS_VIEW', 'View documents and files', 'DOCUMENTS', 'GENERAL', 'VIEW', true, true),
('Manage Backups', 'BACKUPS_MANAGE', 'Create, update, and delete system backups', 'SYSTEM', 'ADMIN', 'ADMIN', true, true),
('View Backups', 'BACKUPS_VIEW', 'View backup information', 'SYSTEM', 'GENERAL', 'VIEW', true, true),
('Approve Certificates', 'CERTIFICATES_APPROVE', 'Approve certificate requests', 'CERTIFICATES', 'APPROVAL', 'APPROVE', true, true),
('Publish Announcements', 'ANNOUNCEMENTS_PUBLISH', 'Publish announcements and notices', 'NOTIFICATIONS', 'PUBLISH', 'PUBLISH', true, true),
('Manage API Keys', 'API_KEYS_MANAGE', 'Manage API keys and integrations', 'SYSTEM', 'ADMIN', 'ADMIN', true, true),
('View API Keys', 'API_KEYS_VIEW', 'View API key information', 'SYSTEM', 'GENERAL', 'VIEW', true, true)
ON CONFLICT (permission_code) DO NOTHING;

-- Insert default role permissions
INSERT INTO role_permissions (role, permission_id, is_active) VALUES
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'DASHBOARD_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'SYSTEM_SETTINGS_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'SYSTEM_LOGS_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'USERS_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'USERS_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'ROLES_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'SCHOOLS_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'SCHOOLS_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'STUDENTS_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'STUDENTS_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'EXAMS_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'EXAMS_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'RESULTS_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'RESULTS_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'FEES_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'FEES_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'CERTIFICATES_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'CERTIFICATES_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'REPORTS_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'REPORTS_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'NOTIFICATIONS_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'NOTIFICATIONS_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'DOCUMENTS_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'DOCUMENTS_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'BACKUPS_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'BACKUPS_VIEW'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'CERTIFICATES_APPROVE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'ANNOUNCEMENTS_PUBLISH'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'API_KEYS_MANAGE'), true),
('SUPER_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'API_KEYS_VIEW'), true),
('DISTRICT_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'DASHBOARD_VIEW'), true),
('DISTRICT_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'SCHOOLS_VIEW'), true),
('DISTRICT_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'STUDENTS_VIEW'), true),
('DISTRICT_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'EXAMS_VIEW'), true),
('DISTRICT_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'RESULTS_VIEW'), true),
('DISTRICT_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'FEES_VIEW'), true),
('DISTRICT_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'CERTIFICATES_VIEW'), true),
('DISTRICT_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'REPORTS_VIEW'), true),
('DISTRICT_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'NOTIFICATIONS_VIEW'), true),
('DISTRICT_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'DOCUMENTS_VIEW'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'DASHBOARD_VIEW'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'STUDENTS_MANAGE'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'STUDENTS_VIEW'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'EXAMS_MANAGE'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'EXAMS_VIEW'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'RESULTS_MANAGE'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'RESULTS_VIEW'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'FEES_MANAGE'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'FEES_VIEW'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'CERTIFICATES_MANAGE'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'CERTIFICATES_VIEW'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'CERTIFICATES_APPROVE'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'REPORTS_VIEW'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'NOTIFICATIONS_MANAGE'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'NOTIFICATIONS_VIEW'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'DOCUMENTS_MANAGE'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'DOCUMENTS_VIEW'), true),
('SCHOOL_ADMIN', (SELECT id FROM permissions WHERE permission_code = 'ANNOUNCEMENTS_PUBLISH'), true),
('TEACHER', (SELECT id FROM permissions WHERE permission_code = 'DASHBOARD_VIEW'), true),
('TEACHER', (SELECT id FROM permissions WHERE permission_code = 'STUDENTS_VIEW'), true),
('TEACHER', (SELECT id FROM permissions WHERE permission_code = 'EXAMS_VIEW'), true),
('TEACHER', (SELECT id FROM permissions WHERE permission_code = 'RESULTS_MANAGE'), true),
('TEACHER', (SELECT id FROM permissions WHERE permission_code = 'RESULTS_VIEW'), true),
('TEACHER', (SELECT id FROM permissions WHERE permission_code = 'CERTIFICATES_VIEW'), true),
('TEACHER', (SELECT id FROM permissions WHERE permission_code = 'REPORTS_VIEW'), true),
('TEACHER', (SELECT id FROM permissions WHERE permission_code = 'NOTIFICATIONS_VIEW'), true),
('TEACHER', (SELECT id FROM permissions WHERE permission_code = 'DOCUMENTS_VIEW'), true),
('STUDENT', (SELECT id FROM permissions WHERE permission_code = 'DASHBOARD_VIEW'), true),
('STUDENT', (SELECT id FROM permissions WHERE permission_code = 'STUDENTS_VIEW'), true),
('STUDENT', (SELECT id FROM permissions WHERE permission_code = 'EXAMS_VIEW'), true),
('STUDENT', (SELECT id FROM permissions WHERE permission_code = 'RESULTS_VIEW'), true),
('STUDENT', (SELECT id FROM permissions WHERE permission_code = 'FEES_VIEW'), true),
('STUDENT', (SELECT id FROM permissions WHERE permission_code = 'CERTIFICATES_VIEW'), true),
('STUDENT', (SELECT id FROM permissions WHERE permission_code = 'NOTIFICATIONS_VIEW'), true),
('STUDENT', (SELECT id FROM permissions WHERE permission_code = 'DOCUMENTS_VIEW'), true),
('PARENT', (SELECT id FROM permissions WHERE permission_code = 'DASHBOARD_VIEW'), true),
('PARENT', (SELECT id FROM permissions WHERE permission_code = 'STUDENTS_VIEW'), true),
('PARENT', (SELECT id FROM permissions WHERE permission_code = 'EXAMS_VIEW'), true),
('PARENT', (SELECT id FROM permissions WHERE permission_code = 'RESULTS_VIEW'), true),
('PARENT', (SELECT id FROM permissions WHERE permission_code = 'FEES_VIEW'), true),
('PARENT', (SELECT id FROM permissions WHERE permission_code = 'CERTIFICATES_VIEW'), true),
('PARENT', (SELECT id FROM permissions WHERE permission_code = 'NOTIFICATIONS_VIEW'), true),
('PARENT', (SELECT id FROM permissions WHERE permission_code = 'DOCUMENTS_VIEW'), true)
ON CONFLICT DO NOTHING;